# Travis CI build configuration config file.

language: php
php:
  - 5.6
# - 7
# - hhvm

addons:
  hosts:
    - localhost
  apt:
    packages:
    # - drush # See: https://github.com/travis-ci/apt-package-whitelist/issues/1611
    - wget
    - realpath
    - tree
    - html2text

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always

# Environment
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
  global:
    - URL="http://$HOSTNAME:8080/"

    - ROOT="$HOME/build/drupal"
    - DRUSH="drush -vy -l '$URL' -r '$ROOT'"
    - COMPOSER_BIN_DIR=~/bin
    - DB_URL="mysql://root:@localhost/drupal"
    - PATH=${PATH//:\.\/node_modules\/\.bin/} # Fixes Travis bug: https://github.com/travis-ci/travis-ci/issues/4862

   ## DRUPAL_TI configuration ##
    - DRUPAL_TI_ENVIRONMENT="drupal-7"
    - DRUPAL_TI_MODULE_NAME="rules_forms"
    - DRUPAL_TI_SIMPLETEST_GROUP="rules_forms"
    - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal"
      # Simpletest specific commandline arguments, the DRUPAL_TI_SIMPLETEST_GROUP is appended at the end.
    - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $URL"
      # PHPUnit specific commandline arguments.
    - DRUPAL_TI_PHPUNIT_ARGS=""
      # Specifying the phpunit-core src/ directory is useful when e.g. a vendor/
      # directory is present in the module directory, which phpunit would then
      # try to find tests in. This option is relative to $TRAVIS_BUILD_DIR.
   #- DRUPAL_TI_PHPUNIT_CORE_SRC_DIRECTORY="./tests/src"
      # Code coverage via coveralls.io
    - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
      # This needs to match your .coveralls.yml file.
    - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
      # Debug options
   #- DRUPAL_TI_DEBUG="-x -v"
      # Set to "all" to output all files, set to e.g. "xvfb selenium" or "selenium",
      # etc. to only output those channels.
   #- DRUPAL_TI_DEBUG_FILE_OUTPUT="selenium xvfb webserver"


  matrix:
    - DRUPAL_TI_RUNNERS="simpletest"
    # DRUPAL_TI_RUNNERS="phpunit"
    #- DRUPAL_TI_RUNNERS="behat"
    #- DRUPAL_TI_RUNNERS="phpunit simpletest behat"

    # Use phpunit-core to test modules with phpunit with Drupal 8 core.
    # Enable php-unit core again once we have working phpunit tests
    - DRUPAL_TI_RUNNERS="phpunit-core"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - env
  - gem install mailcatcher && mailcatcher -v
  - echo 'sendmail_path="/usr/bin/env catchmail"' | tee -a "$(php --ini | grep "Loaded Configuration" | awk '{print $4}')"
  - composer self-update
  - composer global require -n --prefer-source drush/drush:dev-master drupal/coder lionsad/drupal_ti:1.*
  - phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
 #- drupal-ti before_install
 #- set -e # Fail build on first error.

install:
  - drupal-ti install
 #- $DRUSH -vy qd --no-server --watchdog --core=drupal-$CORE testsite
 #- rsync -vuar "$TRAVIS_BUILD_DIR" "$ROOT"/sites/all/modules/contrib
 #- $DRUSH en $TEST_MODULE
 #- $DRUSH dis update
 #- $DRUSH en simpletest

before_script:
  - drupal-ti before_script
 #- $DRUSH -v rs $URL &
  - html2text <(wget -O- --retry-connrefused $URL)
 #- mysql -e 'create database drupal'

script:
  - $DRUSH core-requirements --severity=2 | grep -iw --color=auto error
  - drupal-ti script
  - phpcs -n --standard=Drupal,DrupalPractice --colors --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md $(drush dd $TEST_MODULE)
 #- phpunit -v "$ROOT"/sites/all
 #- php "$ROOT"/scripts/run-tests.sh --color --url $URL --php "$(which php)" --file $(find "$ROOT"/sites/all/modules -name "*.test" | paste -d, -s)

after_success:
 - html2text <(curl http://localhost:1080)

after_failure:
 - $DRUSH status --full
 - $DRUSH core-requirements --severity=2
 - tree -d -L 6 ~/ # Print directory structure in the form of a tree.

after_script:
 - drupal-ti after_script
 - $DRUSH ws --full
 - html2text <(wget -qO- $URL)
